### ISSUE TITLE
deepstack-trainer not working

### ISSUE THREAD

**Issue by xcellenceit** [t0mer/deepstack-trainer#11]
I am setting up a deepstack-trainer using docker-compose but it doesn't seem to work.. not sure what's wrong. 

Note that I am using docker on win 10 machine.

Here is my docker-compose

```
version: "3.9"
services:
  deepstack:
    container_name: deepstack
    restart: unless-stopped
    image: deepquestai/deepstack
    ports:
      - '80:5000'
    environment:
      - VISION-FACE=True
      - VISION-DETECTION=True
      - VISION-SCENE=True
      - API-KEY="deepstack"
    volumes:
      - ./localstorage:/datastore
    networks:
      - deepstacknet
  deepstack_ui:
    container_name: deepstack_ui
    restart: unless-stopped
    image: robmarkcole/deepstack-ui:latest
    environment: 
      - DEEPSTACK_IP=192.168.29.100
      - DEEPSTACK_PORT=80
      - DEEPSTACK_API_KEY="deepstack"
      - DEEPSTACK_TIMEOUT=20
      - DEEPSTACK_UI_DEBUG_MODE=True
    ports:
      - '8501:8501'
    networks:
      - deepstacknet
  deepstack_trainer:
    image: techblog/deepstack-trainer
    container_name: deepstack_trainer
    privileged: true
    restart: always
    environment:
      - DEEPSTACK_HOST_ADDRESS=http://192.168.29.100:80
      - DEEPSTACK_API_KEY="deepstack"
      - MIN_CONFIDANCE=60
    ports:
      - "8080:8080" 
    volumes:
      - ./deepstack-trainer/db:/opt/trainer/db #Database storing the uploaded photos data (Filename, Person name, Date).
      - ./deepstack-trainer/uploads:/opt/trainer/photos/uploads #Phisical path for storing the images
networks:
  deepstacknet:
    driver: bridge
```

Here is the error I am getting..
![image](https://user-images.githubusercontent.com/661269/157851665-bab9e5dc-aa21-4e7b-82d3-70528ba308d2.png)

![image](https://user-images.githubusercontent.com/661269/157851752-69977c30-efcc-459f-bb22-84e8d99b4ade.png)

![image](https://user-images.githubusercontent.com/661269/157851857-6eee28a9-3035-4f9c-a89b-323949f8a394.png)

Pls guide, what could be wrong?

**Comment by t0mer** [comment]
Hi @xcellenceit,
Thanks for pointing it out, I'll check it up.

**Comment by t0mer** [comment]
Fixed.
Please pull the latest version and give it a try.

**Comment by xcellenceit** [comment]
I tried again after pulling the latest image 1.1.0, here is what I get.

![image](https://user-images.githubusercontent.com/661269/158174628-ccc3b51f-b77b-4d8f-9593-17af1e2236ca.png)
![image](https://user-images.githubusercontent.com/661269/158174686-e475dcab-e180-40ea-9a49-7114bf6872e3.png)
![image](https://user-images.githubusercontent.com/661269/158174744-bf6c4e54-1155-4dd9-b984-5347264c223d.png)
![image](https://user-images.githubusercontent.com/661269/158174798-722f18f1-4107-47b8-9c36-de50d2fcdca2.png)


Can you please review and let me know if this part of docker-config is okay?

```
  deepstack_trainer:
    image: techblog/deepstack-trainer:1.1.0
    container_name: deepstack_trainer
    privileged: true
    restart: always
    environment:
      - DEEPSTACK_HOST_ADDRESS=http://192.168.29.100:80
      - DEEPSTACK_API_KEY="deepstack"
      - MIN_CONFIDANCE=60
    ports:
      - "8080:8080" 
    volumes:
      - ./deepstack-trainer/db:/opt/trainer/db #Database storing the uploaded photos data (Filename, Person name, Date).
      - ./deepstack-trainer/uploads:/opt/trainer/photos/uploads #Phisical path for storing the images
```
